telegram:
  enable: false
  tgBotUsername: 'bot'
  tgBotToken: 'token'
  tgAdminChatId: -1
  tournamentChatId: -1
  messagesThreadNumber: 1
  messagesQueueCapacity: 100
discord:
  enable: false
  applicationId: 1245357947564068956
  discordBotToken: 'token'
  discordBotUserId: -1
  discordAdminChatId: -1
  ruNotificationTournamentChannelId: -1
  enNotificationTournamentChannelId: -1
  ruConfirmationTournamentChannelId: -1
  enConfirmationTournamentChannelId: -1
  gameLogsChannelId: -1
  messagesThreadNumber: 1
  messagesQueueCapacity: 100
commandResultQueueCapacity: 100
notificationQueueCapacity: 100
eventsMailboxPool: 2
commandResultHandlerThreadNumber: 5
notificationHandlerThreadNumber: 5
disableOnStart: false
checkNotificationsIntervalInSeconds: 5
tensoulAppToken: 'token'
tensoulUrl: 'http://127.0.0.1:9187'
portalUrl: 'http://127.0.0.1:9999'
autobotApiToken: 'autobot_token'
tournamentId: -1
lobbyId: -1
gamePlatform: tenhou